DROP INDEX IF EXISTS idx_customer_username;
DROP INDEX IF EXISTS idx_customer_email;
DROP INDEX IF EXISTS idx_movie_title;
DROP INDEX IF EXISTS idx_movie_release_date;
DROP INDEX IF EXISTS idx_movie_genre;
DROP INDEX IF EXISTS idx_theater_name;
DROP INDEX IF EXISTS idx_show_movie_id;
DROP INDEX IF EXISTS idx_show_theater_id;
DROP INDEX IF EXISTS idx_show_start_time;
DROP INDEX IF EXISTS idx_promotion_code;
DROP INDEX IF EXISTS idx_promotion_date_range;
DROP INDEX IF EXISTS idx_credit_card_customer_id;
DROP INDEX IF EXISTS idx_credit_card_number;
DROP INDEX IF EXISTS idx_credit_card_name;
DROP INDEX IF EXISTS idx_booking_customer_id;
DROP INDEX IF EXISTS idx_booking_show_id;
DROP INDEX IF EXISTS idx_booking_credit_card_id;
DROP INDEX IF EXISTS idx_booking_promotion_id;
DROP INDEX IF EXISTS idx_booking_date;
DROP INDEX IF EXISTS idx_booking_status;
DROP INDEX IF EXISTS idx_seat_theater_id;
DROP INDEX IF EXISTS idx_ticket_booking_id;
DROP INDEX IF EXISTS idx_ticket_seat_id;

DROP TABLE IF EXISTS ticket CASCADE;
DROP TABLE IF EXISTS seat CASCADE;
DROP TABLE IF EXISTS booking CASCADE;
DROP TABLE IF EXISTS credit_card CASCADE;
DROP TABLE IF EXISTS promotion CASCADE;
DROP TABLE IF EXISTS show CASCADE;
DROP TABLE IF EXISTS theater CASCADE;
DROP TABLE IF EXISTS movie CASCADE;
DROP TABLE IF EXISTS verification_token CASCADE;
DROP TABLE IF EXISTS otp CASCADE;
DROP TABLE IF EXISTS customer_profile CASCADE;
DROP TABLE IF EXISTS app_user CASCADE;
DROP TABLE IF EXISTS user_type CASCADE;